### ISSUE TITLE
Vorgehen Feature Dokumentation [Dev-21.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#46] opened 2022-12-13 14:35 UTC
User story:
**As a** dev
**I want** a clear and concise definition for our way of documentation
**So that** I know how to track progress and document my work

Acceptance criteria:
- Guidelines for documentation for Tickets is written below
- Documentation is done for existing tickets without documentation

Dependencies:
none

How we document:
- Dev/PO tests should be documented by screen recording, and included in the issue
- Changes and decisions during development are documented via comments in the issue
- ...

**Comment by DevJacobi** [comment] 2022-12-20 09:17
Issue is now in progress

**Comment by DevJacobi** [comment] 2022-12-20 09:46
My proposal is the following:

**Ongoing documentation of progress:**

We post every few days an update with information about the status of the issue.
This includes:
- What is done by now
- Screenshots if possible
- If nothing is done, then tell what needs to be done
- If possible, a prediction when it is done

We should post an immediate update:
- If there is a new decision (Talked about in the daily, in some one-on-one meetings, after review or similar)

**Documentation when issue is done**:

If the issue is reviewed and merged it should get an update with documentation of what has changed. This is useful for everybody who is not in our dailys.
This includes:
- Short description about what has changed + a reason why, if something more or less than the issue description has changed.
- What did the changes bring to the codebase? (New dependencies, are there new sites, or components now, some infos a developer could use; Maybe that a new component should be always used this exact way or is designed specifically for this use case, etc.)
- Final screenshots with description if possible


I propose the following template for the documentation when the issue is done (This is based on the points of "Documentation when issue is done") :

_____

**Short description of the change**

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Codebase Changes**

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Visual Documentation**

[Screenshot 1]
Short description
[Screenshot 2]
Short description

_____
@grollk @hstaatsxx @DavidKeanu please give thumbs up or comment suggesting changes

**Comment by hstaatsxx** [comment] 2022-12-20 20:23
Thank you for your suggestion!

**Comment by DevJacobi** [comment] 2022-12-21 12:43
Waiting for thumbs up from @DavidKeanu.
Here is the TODO list for everyone to document the merged features:

@DevJacobi 
- [ ] #37 (when merged)
- [ ] #27 

@hstaatsxx 
- [ ] #33
- [ ] #23 
- [ ] #24
- [ ] #42 (when merged)
- [ ] #29 (when merged)
Some of the issues are for the same feature. If it makes sense to make just one documentation comment, crossreference it in the other issues.

@DavidKeanu 
- [ ] #26
- [ ] #43 (when merged)

Please add any issue that i forgot or that is merged in the meantime!

If every merged issue is documented, this issue can be closed.

**Comment by DevJacobi** [comment] 2023-01-09 16:24
I will close this issue because every developer now knows how to document and has documented every undocumented issue.

**Closed by DevJacobi** 2023-01-09 16:24 UTC
